name: "Install"
description: "Shared setup and install"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
