name: PR Labels

on: pull_request

jobs:
  packages:
    runs-on: ubuntu-latest

    steps:
      - name: Label PR With Repo(s)
        uses: TinkurLab/monorepo-pr-labeler-action@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS: "packages"
        with:
          prefix: "🗂"
